# Generated by Django 2.1.8 on 2019-09-01 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0002_auto_20190827_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acumulado_kpi',
            name='acumulado',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='info_kpi',
            name='fecha_modificacion',
            field=models.DateField(verbose_name=['%d-%m-%Y']),
        ),
    ]
