# Generated by Django 2.1.8 on 2019-09-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0005_auto_20190831_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='nombre_kpi',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
