# Generated by Django 2.1.8 on 2019-09-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0007_auto_20190905_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acumulado_kpi',
            name='fecha',
            field=models.DateField(default='2019-10-01', verbose_name=['%d-%m-%Y']),
            preserve_default=False,
        ),
    ]
