# Generated by Django 2.1.8 on 2019-09-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0008_auto_20190905_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_kpi',
            name='fecha_modificacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
