# Generated by Django 2.1.8 on 2019-09-06 02:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0009_auto_20190905_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acumulado_kpi',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
