# Generated by Django 2.1.8 on 2019-09-06 02:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0010_auto_20190905_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2019, 9, 6, 2, 56, 54, 683292, tzinfo=utc)),
        ),
    ]
