# Generated by Django 2.1.8 on 2019-09-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0011_auto_20190905_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='fecha_creacion',
            field=models.DateField(auto_now=True),
        ),
    ]
