# Generated by Django 2.1.8 on 2019-09-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0012_auto_20190905_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_kpi',
            name='observacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
