# Generated by Django 2.1.8 on 2019-09-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0014_auto_20190906_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='meta_kpi',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
