# Generated by Django 2.1.8 on 2019-09-07 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balance_scorecard', '0015_auto_20190906_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='responsable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info_kpi',
            name='valor_kpi',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
