# Generated by Django 2.1.8 on 2019-09-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0016_auto_20190906_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='nombre_kpi',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
