# Generated by Django 2.1.8 on 2019-09-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0019_auto_20190907_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='nombre_kpi',
            field=models.CharField(error_messages={'no'}, help_text={'cafamos'}, max_length=30, unique=True),
        ),
    ]
