# Generated by Django 2.1.8 on 2019-09-07 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0020_auto_20190907_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='nombre_kpi',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
