# Generated by Django 2.1.8 on 2019-09-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0021_auto_20190907_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_kpi',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
