# Generated by Django 2.1.8 on 2019-09-09 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0022_auto_20190907_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acumulado_kpi',
            name='acumulado',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
