# Generated by Django 2.1.8 on 2019-09-09 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0023_auto_20190908_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acumulado_kpi',
            name='acumulado',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
