# Generated by Django 2.1.8 on 2019-09-09 02:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0024_auto_20190908_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='meta_kpi',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
