# Generated by Django 2.1.8 on 2019-09-09 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0027_compromisos_incidentes_reunion'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisos',
            name='id_incidente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='balance_scorecard.Incidentes'),
            preserve_default=False,
        ),
    ]
