# Generated by Django 2.1.8 on 2019-09-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0029_auto_20190909_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisos',
            name='estado_compromiso',
            field=models.SmallIntegerField(choices=[(1, 'Completada'), (2, 'En Proceso'), (3, 'Pendiente')]),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='categoria',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Financieros'), (2, 'Clientes'), (3, 'Procesos Internos'), (4, 'Aprendizaje y Crecimiento')]),
        ),
    ]
