# Generated by Django 2.1.8 on 2019-09-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0030_auto_20190909_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentes',
            name='titulo_incidente',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
