# Generated by Django 2.1.8 on 2019-09-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0031_auto_20190909_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='acumulado_kpi',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='acumulado_kpi',
            name='proyeccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
