# Generated by Django 2.1.8 on 2019-10-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0037_auto_20191011_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
