# Generated by Django 2.1.8 on 2019-10-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0038_indicador_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='descripcion_kpi',
            field=models.CharField(blank=True, default=3, max_length=100),
            preserve_default=False,
        ),
    ]
