# Generated by Django 2.1.8 on 2019-10-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_scorecard', '0039_auto_20191011_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='descripcion_kpi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='unidad_medida',
            field=models.CharField(blank=True, default=2, max_length=15),
            preserve_default=False,
        ),
    ]
